/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ahebert' at '4/8/16 11:07 AM' with Gradle 2.9
 *
 * @author ahebert, @date 4/8/16 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
